name: Feature Branch
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened, labeled]
  merge_group:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read
  statuses: write

env:
  ATMOS_PROFILE: github

jobs:
  deploy-preview:
    runs-on: ["ubuntu-latest"]
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    name: deploy / preview
    if: >-
      github.event_name == 'pull_request' &&
      contains(github.event.pull_request.labels.*.name, 'deploy')
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.output_url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy ECS Service
        id: deploy
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          atmos terraform deploy app -s preview

  deploy-dev:
    runs-on: ["ubuntu-latest"]
    container:
      image: ghcr.io/cloudposse/atmos:${{ vars.ATMOS_VERSION }}
    name: deploy / dev
    if: github.event_name == 'merge_group'
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.output_url }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Deploy ECS Service
        id: deploy
        run: |
          atmos terraform deploy app -s dev
